name: Build and push a docker on release published

on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  build-tests:
    uses: arensis/nestjs-github-actions-poc/.github/workflows/ci.yml@main
        
  docker:
    needs: [build-tests]
    runs-on: ubuntu-latest

    steps:
    - name: Copy repository
      uses: actions/checkout@v3

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USER }}
        password: ${{ secrets.DOCKER_HUB_PASSWORD }}

    - name: Build and push image with release tag
      if: ${{ github.event_name == 'release' }}
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: ${{ secrets.DOCKER_HUB_REPOSITORY }}:${{ github.event.tag_name }}

    - name: Build and push image with latest tag
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: ${{ secrets.DOCKER_HUB_REPOSITORY }}:latest


    
