name: Manual CI

on:
  workflow_dispatch:

jobs:
  build-test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest]
        node-version: [20.x, 18.x]
    
    steps:
    - name: Copy repository
      uses: actions/checkout@v3

    - name: Build and run test
      uses: ./.github/actions/node-basic-ci-unix-action
      with:
        node-version: ${{ matrix.node-version }}    
