name: print github context properties

on: [workflow_dispatch, release, push]

jobs:
  print-context-variables:
    runs-on: ubuntu-latest

    steps:
      - name: check node version
        run: echo $(node -v)

      - name: check java version
        run: echo $(java --v)

      - name: print short last commit
        env:
          SHORT_COMMIT_HASH: $(echo ${{ github.sha }} | cut -c1-7)
        run: echo "$SHORT_COMMIT_HASH"
        
      - name: print github event name
        run: echo !${{ github.event_name }}!

      - name: github context properties
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      
      - name: vars context properties
        env:
          VARS_CONTEXT: ${{ toJson(vars) }}
        run: echo "$VARS_CONTEXT"
      
      - name: vars context properties
        env:
          INPUTS_CONTEXT: ${{ toJson(inputs) }}
        run: echo "$INPUTS_CONTEXT"

      - name: env context properties
        env:
          ENV_CONTEXT: ${{ toJson(env) }}
        run: echo "$ENV_CONTEXT"
          
