name: print github context properties

on: [workflow_dispatch, release, push]

jobs:
  print-context-variables:
    runs-on: ubuntu-latest

    steps:
      - name: print github event name
        run: echo !${{ github.event_name }}!

      - name: event properties
        env:
          GITHUB_EVENT_CONTEXT: ${{ toJson(github.event) }}
        run: echo "$GITHUB_EVENT_CONTEXT"
          
