name: print github context properties

on: [workflow_dispatch, release, push]

jobs:
  print-context-variables:
    runs-on: ubuntu-latest

    steps:
      - name: print github event name
        run: echo !${{ github.event_name }}!

      - name: github context properties
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
          
