name: print github context properties

on: [workflow_dispatch, release, push]

jobs:
  print-context-variables:
    runs-on: ubuntu-latest

    steps:
      - name: print github event name
        run: echo !${{ github.event_name }}!

      - name: push properties
        if: ${{ github.event_name == 'push' }}
        run: |
          echo !${{ github.event.author }}!
          echo !${{ github.event.comments }}!
          echo !${{ github.event.committedDate }}!
          echo !${{ github.event.committer }}!
          echo !${{ github.event.message }}!
          echo !${{ github.event.oid }}!
          echo !${{ github.event.status }}!
      - name: workflow_dispatch properties
        if: ${{ github.event_name == 'workflow_dispatch' }}
        run: |
          echo !${{ github.event.enterprise }}!
          echo !${{ github.event.inputs }}!
          echo !${{ github.event.installation }}!
          echo !${{ github.event.organization }}!
          echo !${{ github.event.ref }}!
          echo !${{ github.event.repository }}!
          echo !${{ github.event.sender }}!
          echo !${{ github.event.workflow }}!
          
